# Clase 6: Solución de la ecuación de estado y discretización

## Introducción

Hasta ahora encontramos diversas formas de representar sistemas con variables de estado. Descubrimos cómo llegar a estas ecuaciones a partir de la ecuación diferencial o en diferencias de un modelo. Sabemos que podemos aplicar transformaciones, que son cambios de base del espacio de estados, y que nos pueden servir para pasar de una descripción o otra. Nos puede ser útil para simplificar los problemas que vamos a encontrar o para hacer análisis de los sistemas.

Además, vimos una forma particular, llamada de Jordan, que simplifica la ecuación de estados al desacoplar las ecuaciones y dejar expuestos los diversos modos de un sistema. En definitiva, de una forma u otra, llegamos a modelos de la forma:

$$ \dot{x}(t) = A x(t) + B u(t) $$
$$ y(t) = C x(t) + D u(t) $$

o

$$ x(k+1) = A x(k) + B u(k) $$
$$ y(k) = C x(k) + D u(k) $$

dependiendo si el sistema es de tiempo continuo o discreto. También vimos que estos modelos describen posiblemente incrementos alrededor de las trayectorias nominales o puntos de trabajo de los sistemas físicos en estudio.

Nos queda resolver una pregunta: ¿Cuál es la solución de estas ecuaciones? ¿Cómo hallamos la evolución del vector de estado en el tiempo $x(t)$ o $x(k)$?

## Solución y la matriz de transición de estados

Ya vimos en la teórica cuál es la solución de cada una de estas ecuaciones. Para el caso LTI en tiempo continuo:

$$ x(t) = \Phi(t-t_0)x(t_0) + \int_{t_0}^{t} \Phi(t-\tau) B u(\tau) d\tau$$

Donde 

$$ \Phi(t-t_0) = e^{A(t-t_0)} $$

es la matriz de transición de estado en tiempo continuo. En sistemas LTI es igual a la matriz exponencial.

Para el caso LTI en tiempo discreto:

$$ x(k) = \Phi(k -k_0) x(k_0) + \sum_{i=k_0}^{k-1} \Phi(k-i-1) B u(i) $$

Donde 

$$\Phi (k-k_0) = A^{k-k_0}$$

es la matriz de transición de estado en tiempo discreto.

Ambas soluciones poseen dos términos, el primero es la respuesta del estado ante las condiciones iniciales no nulas, también denominada respuesta libre, o con entrada nula. El segundo corresponde a la respuesta forzada o para condiciones iniciales nulas.

### ¿Cómo hallar la matriz de transición de estados?

#### Tiempo continuo

La definición de matriz exponencial es a través de la serie:

$$ e^M = \sum_{i=1}^{\infty} \frac{M^i}{i!} = I + M + \frac{M^2}{2} + \frac{M^3}{6} + ... $$

Y de aparecer el tiempo involucrado, simplemente es un número real a los efectos de su cálculo:

$$ e^{At} = \sum_{i=1}^{\infty} \frac{(At)^i}{i!} = I + At + \frac{A^2 t^2}{2} + \frac{A^3 t^3}{6} + ... $$

Es importante entonces notar que es una matriz $ \in \mathbb{R}^{n\times n}$ , para un vector de estado $x \in \mathbb{R}^n$. Y por más que la definición lo indica, aclaramos que no es lo mismo hacer la exponencial de cada elemento de la matriz.

#### Tiempo discreto

La matriz de transición de estados en tiempo discreto es mucho más simple de hallar:

$$ \Phi(k - k_0) = A^{k-k_0}$$

En donde la potencia $k-k_0$ es un número natural representando las $k-k_0$ transiciones del vector de estado, y en el caso que $k = k_0$, $\Phi(0) = I_{n\times n}$. Para obtenerla, se debe calcular simplemente de la siguiente manera:

$$ \Phi(k-k_0) = \underbrace{A A \dots A}_{k-k_0 \text{veces}} $$

### Ejemplo: Cálculo de la matriz exponencial con A diagonalizable.

Dado el sistema:

$$\dot{x} = A x$$

Con

$$ A = \begin{bmatrix} -7 & 2 & 1\\ 4 & -5 & -4\\ 0 & 0 & -6 \end{bmatrix} $$

y condición inicial $x_0 = \begin{bmatrix} 0 & 0 & 1 \end{bmatrix}^T$

Queremos calcular la evolución del sistema desde $x(0)=x_0$ hasta $x(5)$.

Para esto necesitamos la matriz de transición de estados:

$$ x(t_1) = \Phi(t_1-t_0) x(t_0) $$

Que en el caso de $t_1 = 5$, $t_0 = 0$, y el sistema LTI es:

$$ x(5) = e^{5A}x(t_0) $$

Si A es diagonalizable:

$$A = M \Delta M^{-1}$$

Luego, aplicamos la definición:

$$ e^{5A} = \sum_{i=1}^{\infty} \frac{(5A)^i}{i!} =  \sum_{i=1}^{\infty} \frac{5^i (M \Delta M^{-1})^i}{i!} $$

Notamos que la potencia $i$ de las matrices da:

$$ (M\Delta M^{-1} )^i =  M \Delta \underbrace{M^{-1} M}_I \Delta M^{-1} \dots M \Delta \underbrace{^{-1} M}_I \Delta M^{-1}= M \Delta^i M^{-1} $$

Y por ser matriz diagonal, la potencia $i$ de $\Delta$ se calcula mucho más fácil. Salen las matrices M y su inversa de la sumatoria como factores comunes a izquierda y a derecha, y queda:

$$ e^{5A} = M E M^{-1} $$

Donde cada elemento de la diagonal de E será:

$$ e_{jj} = \sum_{i=1}^{\infty} \frac{\lambda_j^i 5^i}{i!} = e^{5\lambda_j}$$

El cálculo de la matriz exponencial queda:

$$ e^{5A} = M \begin{bmatrix} e^{5\lambda_1} & 0 & 0 \\ 0 & e^{5\lambda_2} & 0 \\ 0 & 0 & e^{5\lambda_3}\end{bmatrix} M^{-1} $$

El resultado buscado es:

$$ x(5) =  M \begin{bmatrix} e^{5\lambda_1} & 0 & 0 \\ 0 & e^{5\lambda_2} & 0 \\ 0 & 0 & e^{5\lambda_3}\end{bmatrix} M^{-1}x(t_0) $$

Resolvemos por simulación:

In [1]:
import numpy as np
from scipy.linalg import expm

A = np.matrix([[-7, 2, 1],[4, -5, -4],[0, 0, -6]])
x01 = np.matrix([[0],[0],[1]])
t = 5

autoval, M = np.linalg.eig(A)
D = np.diag(autoval)
print('\n D =', D)
print('\n M =', M)


 D = [[-9.  0.  0.]
 [ 0. -3.  0.]
 [ 0.  0. -6.]]

 M = [[-7.07106781e-01 -4.47213595e-01  7.07106781e-01]
 [ 7.07106781e-01 -8.94427191e-01  1.58187870e-17]
 [ 0.00000000e+00  0.00000000e+00  7.07106781e-01]]


Como es diagonalizable podemos continuar con el procedimiento propuesto.

In [2]:
D_5 = np.diag(np.exp(t*autoval))
x5 = M*D_5*np.linalg.inv(M)*x01
print('El estado en t =', t, 'vale \n x=\n', x5)

El estado en t = 5 vale 
 x=
 [[-1.01967347e-07]
 [-2.03934880e-07]
 [ 9.35762297e-14]]


Podemos verificar con el cálculo directo:

In [3]:
x5 = expm(t*A)*x01
print('El estado en t =', t, 'vale \n x=\n', x5)

El estado en t = 5 vale 
 x=
 [[-1.01967347e-07]
 [-2.03934880e-07]
 [ 9.35762297e-14]]


## Discretización exacta

Una aplicación interesante de la solución de la ecuación de estado en tiempo continuo es la discretización de un sistema para hallar un sistema en tiempo discreto equivalente. Repasamos primero esta idea a continuación.

Queremos desarrollar un controlador en tiempo discreto del sistema:

$$ \dot{z} = A z + B u $$
$$ y = C z + D u $$

con una computadora. Para ello ya sabemos que vamos a tener que elegir un tiempo de muestreo $T_S$ acorde a nuestros objetivos de control, las características del sistema a controlar y las capacidades de cálculo de nuestra computadora. Cada $T_S$ segundos vamos a estar muestreando la señal de interés o salida $y(t). 

Asimismo, vamos a tener que definir cómo vamos a accionar la entrada de este sistema. El controlador va a calcular cada $T_S$ segundos un valor actualizado de acción de control $u(t)$. Una de las formas más simples de generar esta señal, es dejar su valor constante durante el período de muestreo. Es lo que se conoce como retenedor de orden cero  o ZOH, que viene del inglés _zero order hold_.

El esquema que ejecuta estas dos acciones, la de muestrear $y(t)$ y la de retener el valor de $u(t)$, es el siguiente:

<figure>
<center>
<img src='https://drive.google.com/uc?id=1IFMfkWQBZ_x4IpwSaGHSy61irY4irEM9'/>
<figcaption>Retenedor y muestreo para discretizar</figcaption></center>
</figure


De donde se va a obtener un sistema en tiempo discreto equivalente de la forma:

$$ z(k+1) = A_d z(k) + B_d u(k) $$
$$ y(k) = C z(k) + D u(k) $$

Esto es, nos podemos olvidar del sistema en tiempo continuo y directamente trabajar con el nuevo modelo en tiempo discreto para diseñar un controlador como indica la siguiente figura:

<figure>
<center>
<img src='https://drive.google.com/uc?id=1n7XTkE99YPE23bjuF0YyXb65X4C7kgj_'/>
<figcaption>Sistema equivalente con controlador digital</figcaption></center>
</figure

Y luego, volver al sistema físico y aplicar la ley de control encontrada.

Partimos entonces de $t_0 = kT_S$, que en la solución de la ecuación de da que:

$$ z(t) = e^{A(t-k T_S)}z(kT_S) + \int_{kT_S}^{t} e^{A(t-\tau)} B u(\tau) d\tau$$

Y calculamos cómo evoluciona el estado durante un período de muestreo, o sea hasta $t = kT_S + T_S$:

$$ z(kT_S+T_S) = e^{AT_S}z(kT_S) + \int_{kT_S}^{kT_S+T_S} e^{A(kT_S+T_S-\tau)} B u(\tau) d\tau$$

De allí sale, si consideramos el efecto del ZOH, que:

$$ z(k+1) = A_d z(k) + B_d u(k) $$

Con 

$$ A_d = e^{AT_S} $$

y 

$$ B_d = \int_0^{T_S} e^{A\alpha} d\alpha B $$

**Ejercicio:** Demostrar el paso para hallar la expresión de $B_d$.

Para los casos en donde A no es inversible, no nos servirá la expresión para $B_d$ encontrada en la clase teórica. Entonces, en el caso más general deberemos hallar una expresión de la función matricial $\Phi(t) = e^{At}$ para luego integrar y calcular $B_d$ con la expresión dada.

¡Probemos esta discretización con un ejemplo!

## Tarea:

Dado el circuito RLC de la clase 3, propongo hallar un sistema en tiempo discreto equivalente con el método de discretización exacta.

La ecuación de estado era:

$$ \mathbf{\dot{x}} =  \begin{bmatrix} 0 & 1\\ -\frac{1}{LC} & -\frac{2}{RC} \end{bmatrix} \mathbf{x} + \begin{bmatrix} 0 \\ 1\end{bmatrix} u$$

$$ y = \begin{bmatrix}-\frac{1}{LC} -\frac{1}{RC} \end{bmatrix} \mathbf{x} + u $$

1. Convertir el sistema a la forma de Jordan. Dejar expresada la ecuación de estado en su forma con coeficientes reales. Usar como pista el ejercicio 7 de la guía 2.
2. Seleccionar un valor de $T_S$ que considere adecuado. Explicar el criterio adoptado.
3. Aplicar la discretización exacta.
4. Aplicar la discretización aproximada (repasar los primeros minutos de https://youtu.be/jkW_Lco_A50). ¿Cómo se relaciona esta aproximación con la que hicimos en la clase 3?
5. Comparar la respuesta al escalón de las dos discretizaciones, exacta y aproximada, y con la del sistema en tiempo continuo original.
6. Explorar la función directa que le proporciona el simulador para discretizar y verifique el método que utiliza.

In [4]:
# Aquí va tu código
!pip install control
import numpy as np
import control as ctrl
import matplotlib.pyplot as plt

R = 20  # Ohm
C = 5e-6  # F
L = 10e-6  # H
# Ts = ... Completá con el valor que creas adecuado

     |████████████████████████████████| 339 kB 5.3 MB/s 
  Created wheel for control: filename=control-0.9.0-py2.py3-none-any.whl size=344928 sha256=344d1a5f23776191e0926912be8363bcdff6862659e0b04c2728f8047778e574
  Stored in directory: /root/.cache/pip/wheels/5b/64/54/70faad181d7baff1184541ca00c9a2efa633acd0a811831d30
Successfully built control
